### PR TITLE
Add github actions

### PR DESCRIPTION
**Pull request by hellerve**
This PR adds a Github action. I have literally no idea what I’m doing, and I expect this to be broken.

Cheers

### CODE REVIEW

**Comment by hellerve** [comment]
Okay, so this should be good to go now. It’s still failing, because Black is failing (see #4, which resolves this). Once #4 is merged, we can rebase this PR and check out whether it works as expected.

Also, Github actions are weird.

**Review by dbalan — APPROVED** [review]
Just to confirm: this would fail if there are linter errors, not reformat the code - right?

**Comment by hellerve** [comment]
Yes, it runs in `--check` mode, effectively telling the maintainer to reformat.

**Comment by hellerve** [comment]
The linter works! Yay!

**Pull request merged**
